### ISSUE TITLE
See if syncHeightResponsive can be made generic

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-content-bootstrap3#1]
ensure syncHeightResponsive always works, the current implementation sometimes includes the script, but it's not called, or the  
  anchor for it is a template specific wrapper - i think this should be simpler, like "co-sync-height-container" and "co-sync-height-element"

**Comment by rf-999** [comment]
fyi: with upcoming Flexbox support this can be made possible exclusively with CSS.

Search for: flexbox equal height 
Current Flexbox browser support: http://caniuse.com/#feat=flexbox

**Comment by iJungleboy** [comment]
We tried that, but it's not reliable yet, so for now we have to stay with this.
